### ISSUE TITLE
Unable to locate package php5-xdebug

### ISSUE THREAD

**Issue by ricardollerenad** [jobcespedes/docker-compose-moodle#1]
After do, all thing like de readme.md say, it throw this error:

E: Unable to locate package php5-xdebug
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends php5-xdebug &&     apt-get install -y --no-install-recommends libxml2-dev zlib1g-dev libpng12-dev         libfreetype6-dev libjpeg62-turbo-dev libicu-dev libpspell-dev libpq-dev libldap2-dev libxslt-dev &&     docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/         --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ &&     docker-php-ext-install gd &&     docker-php-ext-configure xmlrpc --with-libxml-dir=/usr/include/ &&     docker-php-ext-install xmlrpc &&     docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu &&     docker-php-ext-install ldap &&     docker-php-ext-install soap zip intl pspell pgsql xsl &&     docker-php-ext-configure opcache --enable-opcache && docker-php-ext-install opcache' returned a non-zero code: 100

any idea??

**Comment by jobcespedes** [comment]
Please pull latest commit and let me know if it works.
