### ISSUE TITLE
Reason: DNS lookup failure for: php-fpm

### ISSUE THREAD

**Issue by juliorod63** [jobcespedes/docker-compose-moodle#10]
Hola,
cuando intento conectarme con Moodle, me aparece este mensaje:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: DNS lookup failure for: php-fpm

Apache/2.4.25 (Debian) Server at 127.0.0.1 Port 80

Al parecer no me levanta en Docker docker-compose-moodle_php-fpm_1metics/php-fpm:7

Se inicia y se apaga
En los log solo me indica: : invalid option

Tampoco levanta este docker: docker-compose-moodle_app_1tianon/true
aunque me da Exit Code 0

Gracias.

**Comment by jobcespedes** [comment]
Hola,

El exit code de moodle_app es correcto. Solo comparte directorios entre el host y otros contenedores. 

Sobre el error, podrían ser de ayuda los siguientes datos:

Sistema operativo:
Versión de docker `docker version`:
Salida de ejecutar `docker-compose logs php-fpm`:

**Comment by juliorod63** [comment]
Hola, 
te facilito los datos:
**Sistema Operativo**: del Docker es Linux, de mi equipo Windows 10.
**Version de Docker Server**: 
Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false

Los logs de salida de esa instancia:
: invalid option

en la parte de inspect, veo que el Port 9000/tcp  indica Not Binded.

Mucas gracias.

**Comment by jobcespedes** [comment]
Sí. El problema parece estar en el contendor php-fpm. Pero los logs que solo muestran `: invalid option` no dicen mucho. El servicio de docker podría tener más información en sus logs, a la hora de intentar iniciar de nuevo ese contenedor.

**Comment by juliorod63** [comment]
No arroja mucha mas informacion, al menos con el comando docker-compose logs:

PS C:\volumen\moodle-compose\docker-compose-moodle> docker-compose logs php-fpm 
Attaching to docker-compose-moodle_php-fpm_1
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option
[36mphp-fpm_1   |[0m /bin/bash: -
: invalid option

**Comment by juliorod63** [comment]
y con la imagen docker-compose-moodle_cron_1metics/php-fpm:7-cron

me pasa exactamente lo mismo, termina con codigo exit 1 y arroja :invalid option en el log.

**Comment by jobcespedes** [comment]
Me refería a los logs de dockerd propiamente. No estoy familiarizado con el entorno Windows. No podría indicarle como verlos. Pero talvez el servicio dockerd tengan más info.

**Comment by jobcespedes** [comment]
Adicionalmente, se podría probar obtener más información con los siguientes comandos:
```bash
docker run -ti --rm --entrypoint /bin/bash metics/php-fpm:7
sed -i "s@bash -e.*@bash -ex@" /usr/local/bin/php-fpm-xdebug-entrypoint
sed -i "s@set -e.*@set -ex@" /usr/local/bin/docker-php-entrypoint
/usr/local/bin/php-fpm-xdebug-entrypoint php-fpm -v
```
Y poner atención a la salida del último comando

**Comment by Pra3t0r5** [comment]
Referente a este problema, a veces me pasa lo mismo. 

Las primeras veces que me paso lo resolvi con un `prune` completo de docker, luego cai en la cuenta de que hacia falta usar la opcion `--volumes` para limpiar correctamente antes de hacer un nuevo `up -d`.

Sin embargo eso no siempre resuelve el problema, me ha llegado a pasar de tener que borrar completamente el proyecto y reinstalarlo para que vuelva a funcionar.

En esta ultima instancia, creo que el problema me esta surjiendo de haber tocado algunos entrypoints, el docker-compose principal y las env, intentando acoplar mis propias variables de entorno para que peguen en el contenedor al instanciarlo. ([con motivo de configurar esto](https://github.com/harregoces/moodle-enrol_mercadopago))

Por las dudas dejo aqui mis resultados de la ejecucion de los comandos que pasaste, capaz sean de utilidad:
```
~/Projects/wordpress/docker-compose-moodle · (mercadopago±)
⟩ docker-compose logs php-fpm
Attaching to docker-compose-moodle_php-fpm_1
php-fpm_1   | sed: no input files
php-fpm_1   | sed: no input files

~/Projects/wordpress/docker-compose-moodle · (mercadopago±)
⟩ docker run -ti --rm --entrypoint /bin/bash metics/php-fpm:7
  
root@56c531bd5f11:/var/www/html# sed -i "s@bash -e.*@bash -ex@" /usr/local/bin/php-fpm-xdebug-entrypoint
root@56c531bd5f11:/var/www/html# sed -i "s@set -e.*@set -ex@" /usr/local/bin/docker-php-entrypoint
root@56c531bd5f11:/var/www/html# /usr/local/bin/php-fpm-xdebug-entrypoint php-fpm -v
+ '[' -z ']'
++ awk 'END{print $1}' /etc/hosts
++ awk -F . '{print $1 "." $2 "." $3 "." 1}'
+ gateway=172.17.0.1
+ sed -i s@dockerhost@172.17.0.1@ /usr/local/etc/php/conf.d/xdebug.ini
+ '[' -f /usr/local/share/ca-certificates/custom-ca.crt ']'
+ docker-php-entrypoint php-fpm -v
+ [ php-fpm != php-fpm ]
+ exec php-fpm -v
Cannot load Zend OPcache - it was already loaded
[04-Dec-2020 21:07:20 UTC] Xdebug: [Config] The setting 'xdebug.remote_connect_back' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_connect_back (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
[04-Dec-2020 21:07:20 UTC] Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
[04-Dec-2020 21:07:20 UTC] Xdebug: [Config] The setting 'xdebug.remote_host' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_host (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
[04-Dec-2020 21:07:20 UTC] Xdebug: [Config] The setting 'xdebug.remote_log' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_log (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
[04-Dec-2020 21:07:20 UTC] Xdebug: [Config] The setting 'xdebug.remote_mode' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_mode (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
[04-Dec-2020 21:07:20 UTC] Xdebug: [Config] The setting 'xdebug.remote_port' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_port (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
PHP 7.2.34 (fpm-fcgi) (built: Nov 18 2020 11:49:45)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans
root@56c531bd5f11:/var/www/html# exit
exit

```

## Esta fue la aproximacion que rompio mi proyecto, aun estoy buscando solucion

```env
# APP
REPO_FOLDER=html
DOCUMENT_ROOT=/var/www/html
MY_TZ=America/Argentina/Buenos_Aires
# Postgres
PG_LOCALE=es_AR
PG_PORT=5432
POSTGRES_DB=moodle
POSTGRES_USER=admin
POSTGRES_PASSWORD=admin
# FPM
PHP_SOCKET=9000
# APACHE2
ALIAS_DOMAIN=localhost
WWW_PORT=5051
# MOODLE
MOODLE_DATA=/var/moodledata
WWWROOT=localhost
# GENERAL
IP=127.0.0.1
# MERCADOPAGO
MERCADOPAGO_SANDBOX=true
MERCADOPAGO_SANDBOX_EMAIL=fernando.albertengo@gmail.com

```
### docker-compose.yml raiz
```yml
  # Servicio de PHP-FPM
  php-fpm:
    image: "metics/php-fpm:7"
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
      args:
        - DOCUMENT_ROOT
        - MY_TZ
    environment:
      - XDEBUG_CONFIG=idekey=PHPTEST
      - PHP_IDE_CONFIG=serverName=localhost
      - DOCUMENT_ROOT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MOODLE_DATA
      - WWWROOT
      - WWW_PORT
      - MERCADOPAGO_SANDBOX
      - MERCADOPAGO_SANDBOX_EMAIL
```
### php-fpm/conf/php-fpm-xdebug-entrypoint.sh
```bash
        -e  "s@^\$CFG->wwwroot.*@\$CFG->wwwroot    = 'http://${host_port}';@" \
        -e  "s@^\$CFG->dataroot.*@\$CFG->dataroot    = '${MOODLE_DATA}';@" \
        -e  "s@^\$CFG->usemercadopagosandbox.*@\$CFG->usemercadopagosandbox    = '${MERCADOPAGO_SANDBOX}';@" \
        -e  "s@^\$CFG->mercadopagosandbox_email.*@\$CFG->mercadopagosandbox_email    = '${MERCADOPAGO_SANDBOX_EMAIL}';@" \
        ${DOCUMENT_ROOT}/config.php
```
Tambien intente añadiendo las configs directamente a `html/config.php` pero es evidente que el entrypoint o alguna parte del proceso de alta de los contenedores la sobreescribe, razon por la cual intente agregar mis propias variables de entorno.

**Comment by jobcespedes** [comment]
Este tema se cerrerá. Inicialmente no se diseño para un entorno en Windows. Sería genial cualquier colaboración para lograrlo. De momento, se cierra el tema.
