### ISSUE TITLE
Problem dumping postgres and persisting work

### ISSUE THREAD

**Issue by Pra3t0r5** [jobcespedes/docker-compose-moodle#11]
I've been working on a site using your (quite amazing) repo, now i want to save my progress but im getting these errors:
```bash
~/Projects/wordpress/moodle/docker-compose-moodle · (master±)
⟩ ./pg_dump.sh
ERROR: No container found for postgres_1

~/Projects/wordpress/moodle/docker-compose-moodle · (master±)
⟩ ./pg_dump.sh
ERROR: No such service: ultracore-moodle_postgres_1
```
pg_dump, contains:
```bash
#!/bin/bash -e

POSTGRES_DB=moodle
POSTGRES_USER=admin
#tried with postgres, postgres_1, ultracore-moodle_postgres, ultracore-moodle_postgres_1
DB_DUMP_NAME=dump-init.$(date +"%Y%m%d%H%M%S").dump
docker-compose exec ultracore-moodle_postgres_1 pg_dump -U ${POSTGRES_USER} ${POSTGRES_DB} -Fc -f /opt/db_dumps/${DB_DUMP_NAME}
```
And this is my docker status:
```bash
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                           NAMES
2181fb381c14        metics/php-fpm:7-cron       "php-fpm-xdebug-entr…"   2 hours ago         Up 2 hours          9000/tcp                        ultracore-moodle_cron_1
cb6fa2101f8d        metics/apache2:2.4          "/opt/docker/bin/ent…"   2 hours ago         Up 2 hours          127.0.0.1:80->80/tcp, 443/tcp   ultracore-moodle_apache2_1
d363049fac79        metics/php-fpm:7            "php-fpm-xdebug-entr…"   2 hours ago         Up 2 hours          9000/tcp                        ultracore-moodle_php-fpm_1
628e3af27cae        foxylion/pgadmin4           "python ./usr/local/…"   2 hours ago         Up 2 hours          127.0.0.1:5050->80/tcp          ultracore-moodle_pgadmin_1
c21f5f1a3d2d        metics/postgres:9.6-es_AR   "docker-entrypoint.s…"   2 hours ago         Up 2 hours          5432/tcp                        ultracore-moodle_postgres_1
```
```bash
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
metics/postgres         9.6-es_AR           f9008cbd8015        About an hour ago   204MB
metics/php-fpm          7-cron              547a63327e8a        25 hours ago        741MB
metics/apache2          2.4                 1dd23bc36979        25 hours ago        338MB
metics/php-fpm          7                   313c8cbdbc43        25 hours ago        678MB
metics/postgres         9.6-es_CR           7a5d2c51c264        25 hours ago        204MB
```

What i'm doing wrong?
Also, how do i persist my changes? (ie. themes, design, site content data, plugins, etc).
Thank you very much!

**Comment by jobcespedes** [comment]
Hi,

Try replacing the service name parameter: `ultracore-moodle_postgres_1` with just `postgres`. Checkout [the example here](https://github.com/jobcespedes/docker-compose-moodle/blob/master/README.md#backup-and-restore-database).
Ej:
```
docker-compose exec postgres pg_dump -U ${POSTGRES_USER} ${POSTGRES_DB} -Fc -f /opt/db_dumps/${DB_DUMP_NAME}
```
About persisting data or migrating, take into account 3 directories: 
1. Database data: The dump you are trying to create will be at `db_dumps` host dir (relative to your project).
2. Moodle data: `moodledata` host dir (relative to your project).
3. Moodle code: Moodle `REPO_FOLDER` is by default at `html` host dir (relative to your project)

**Comment by jobcespedes** [comment]
One more thing, data will be persisted in the local container engine. 1) Database is using a container volume, 2) Moodledata is stored in the host as well as 3) Moodle code. If you want to migrate or instantiate in a diferent project using same data, then you would need those three things.

**Comment by Pra3t0r5** [comment]
Got it, awesome! Thanks!
Another question, when configuring the `.env` like this:
```.env
# APP
REPO_FOLDER=html
DOCUMENT_ROOT=/var/www/html
MY_TZ=America/Argentina/Buenos_Aires
# Postgres
PG_LOCALE=es_AR
PG_PORT=5432
POSTGRES_DB=moodle
POSTGRES_USER=ucadmin
POSTGRES_PASSWORD=Ucadmin123
# FPM
PHP_SOCKET=9000
# APACHE2
ALIAS_DOMAIN=localhost
WWW_PORT=80
# MOODLE
MOODLE_DATA=/var/moodledata
WWWROOT=localhost
# GENERAL
IP=127.0.0.1
```
I can't connect to my `POSTGRES_DB` directly, if set to moodle it rejects the connection: 
![Screenshot from 2020-11-11 11-10-12](https://user-images.githubusercontent.com/38087682/98822440-a1a53400-240f-11eb-8d68-f19ddab11aed.png)

However, if i connect to `postgres` it does connects with these results:
![Screenshot from 2020-11-11 11-12-37](https://user-images.githubusercontent.com/38087682/98822416-96ea9f00-240f-11eb-9fa3-24a799775249.png)

![Screenshot from 2020-11-11 11-13-25](https://user-images.githubusercontent.com/38087682/98822490-aff35000-240f-11eb-9997-8f3322280d12.png)

2 Databases? Is that correct? I suppose i must aim dumping and restoring to `moodle` database since it's the one i aimed everything at `.env` right?

**Comment by jobcespedes** [comment]
Hi,

"Hostname/address" should be 'postgres'. It's the database container. 'postgres' resolves using docker internal dns lookup. In addition, username and password should be, 1) the ones in `.env` file and 2) database should have being initially started with those credentials.

**Comment by Pra3t0r5** [comment]
Amazing, thank you very much!

**Comment by Pra3t0r5** [comment]
@jobcespedes Hi again! Today i tested a migration from a development environment to a production one, and its giving me this error:
```html
Fatal error: $CFG->dataroot is not writable, admin has to fix directory permissions! Exiting.
```
I've checked the community, and seems like its a very common issue. Thus i gave the corresponding permissions:
```bash
~/docker-compose-moodle$ ls -alh
total 104K
drwxr-xr-x 13 fernando fernando 4.0K Nov 24 18:02 .
drwxr-xr-x  4 fernando fernando 4.0K Nov 19 17:17 ..
-rwxr-xr-x  1 fernando fernando  349 Nov 27 16:17 .env
drwxr-xr-x  8 fernando fernando 4.0K Nov 27 16:12 .git
-rw-r--r--  1 fernando fernando   95 Nov 16 16:38 .gitignore
-rw-r--r--  1 fernando fernando  174 Nov 16 16:25 .travis.yml
-rwxrwxr-x  1 fernando fernando  12K Nov 16 16:25 LICENSE
-rwxrwxr-x  1 fernando fernando  15K Nov 16 16:25 README.md
drwxrwxr-x  2 fernando fernando 4.0K Nov 16 16:25 apache2
drwxrwxr-x  3 fernando fernando 4.0K Nov 16 16:25 cron
-rwxrwxr-x  1 fernando fernando  218 Nov 24 18:02 db_dump.sh
drwxrwxr-x  2 fernando fernando 4.0K Nov 16 16:25 db_dumps
-rwxrwxr-x  1 fernando fernando 2.6K Nov 16 16:25 docker-compose.yml
drwxrwxr-x  3 fernando fernando 4.0K Nov 16 16:25 docs
drwxrwxr-x 52 fernando fernando 4.0K Nov 27 16:19 html
drwxrwxr-x  2 fernando fernando 4.0K Nov 16 16:25 log
-rwxrwxr-x  1 fernando fernando  404 Nov 16 16:38 moodle.code-workspace
drwxrwxr-x  9 fernando fernando 4.0K Nov 19 15:38 moodledata
drwxrwxr-x  3 fernando fernando 4.0K Nov 16 16:25 php-fpm
drwxrwxr-x  3 fernando fernando 4.0K Nov 16 16:25 postgres
drwxrwxr-x  3 fernando fernando 4.0K Nov 16 16:25 test
```
But the error persists, what should i do?

EDIT: fernando:fernando is my server account with limited access (i can only modify things inside my home, but as far as i understand, that should not be a problem since there is no need to access anything outside the proyect folder.

**Comment by jobcespedes** [comment]
Hi

User id inside the container is different from the host's. You could probably solved that difference setting permissions to dataroot (moodledata) to 777.  Ex: `chmod 777 -R moodledata`

If you want to verify user id from host and container, 
- In your host, you can get it with `id -u`
- In the container, use `docker-compose exec php-fpm id -u`

**Comment by Pra3t0r5** [comment]
Nice, now it does not crashes, instead it shows the initial Moodle installation procedure. This means it is not recognizing my moodledata?

This is my .env, just in case:
```bash
# APP
REPO_FOLDER=html
DOCUMENT_ROOT=/var/www/html
MY_TZ=America/Argentina/Buenos_Aires
# Postgres
PG_LOCALE=es_AR
PG_PORT=5432
POSTGRES_DB=moodle
POSTGRES_USER=user
POSTGRES_PASSWORD=password
# FPM
PHP_SOCKET=9000
# APACHE2
ALIAS_DOMAIN=xx.xxx.xx.xxx
WWW_PORT=5051
# MOODLE
MOODLE_DATA=/var/moodledata
WWWROOT=xx.xxx.xx.xxx
# GENERAL
IP=xx.xxx.xx.xxx
```

EDIT:
![Screenshot from 2020-11-27 17-42-42](https://user-images.githubusercontent.com/38087682/100483523-08953f00-30d8-11eb-9b9f-f5962e4799ca.png)
![Screenshot from 2020-11-27 17-42-37](https://user-images.githubusercontent.com/38087682/100483525-09c66c00-30d8-11eb-91ad-132e8ada750a.png)

**Comment by jobcespedes** [comment]
It means 'moodle' database is empty

**Comment by Pra3t0r5** [comment]
Almost facepalmed my face off, I completely forgot to restore the db!
Thank you very much sir!
