### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Pra3t0r5** [jobcespedes/docker-compose-moodle#13]
I'm starting to have a somewhat bad UX because of long response delays (~4 to 15 seconds depending on the task), even if i'm the only one using it (and the server where it is running is quite powerful)
I was wondering if you have had a similar problem, and if so, how did you tackle it?

**Comment by jobcespedes** [comment]
Hi,

This project has been used mainly for developing. It has some config tuning but only for basic moodle develop instances. In case of perfomance tuning, it might be a good idea to check every component config as well as moodle and docker itself.  

I would start checking the logs and trying to figure out what component is the bottleneck: apache, php-fpm, postgres, docker or moodle. 

You might want to check out some links about [moodle perfomance](https://docs.moodle.org/310/en/Performance_recommendations) (if not already).

It might be possible that docker itself is [preventing more resources provision](https://docs.docker.com/config/containers/resource_constraints/). However, I not sure if it does it by default.
