### ISSUE TITLE
No puedo activar el contenedor metics/php-fpm:7

### ISSUE THREAD

**Issue by aquesadagt** [jobcespedes/docker-compose-moodle#3]
No consigo activar el contenedor metics/php-fpm:7
Cuando lo intento me aparece el siguiente error

```
: invalid optionin/bash: -
docker-compose-moodle_php-fpm_1 exited with code 1
```

No he tocado ninguna configuración, está todo como cuando lo descargué.

¿Podrías ayudarme?

**Comment by jobcespedes** [comment]
Hola:

Por favor compartir 1) versión de docker; 2) versión de docker-compose; 3) detalle de Sistema Operativo; y 4) comando ejecutado. Para las dos primeras puede utilizar:

`docker -v`
`docker-compose --version`

Saludos,

**Comment by jobcespedes** [comment]
También compartir los logs de ese contenedor. Ej:

`docker-compose --tail="30" php-fpm`

Y el estado de los contenedores con:

`docker-compose ps`

**Comment by jobcespedes** [comment]
Sin actividad
