### ISSUE TITLE
Error por versión de php

### ISSUE THREAD

**Issue by AFelipeTrujillo** [jobcespedes/docker-compose-moodle#4]
Hola @jobcespedes, gran trabajo ... me surgió el siguiente error: 

![Captura de Pantalla 2020-02-03 a la(s) 12 08 03 p  m](https://user-images.githubusercontent.com/5275376/73674246-1c217600-467e-11ea-8404-26bad4236aa9.png)

Debes solo actualización en el **DOCKERFILE**

**Comment by jvinolas** [comment]
Hay que cambiar la imágen base del Dockerfile de php-fpm

> FROM php:7.1-fpm-stretch

Ya hace build

**Comment by jvinolas** [comment]
Si vais a usar una versión superior de moodle (creo que >3.7) sólo va con 7.2!

> FROM php:7.2-fpm-stretch

**Comment by jobcespedes** [comment]
Hola:

Gracias por reportar el error. Pronto lo corregiré en la rama master.  Sigue la última versión de soporte extendido de Moodle (LTS). Es la versión 3.5.
