### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by pol-todo** [jobcespedes/docker-compose-moodle#5]
Hi Job,

Followed your quick start instructions, and I'm seeing this error and was curious if I was doing something wrong?

- Paul

```
the following information may help to resolve the situation:

The following packages have unmet dependencies:
 clamav : Depends: clamav-freshclam (>= 0.102.2+dfsg) but it is not going to be installed or
                   clamav-data
          Depends: libc6 (>= 2.28) but 2.24-11+deb9u4 is to be installed
          Depends: libclamav9 (>= 0.102.2) but it is not going to be installed
          Depends: libcurl4 (>= 7.16.2) but it is not installable
 clamav-daemon : Depends: clamav-freshclam (>= 0.102.2+dfsg) but it is not going to be installed or
                          clamav-data
                 Depends: libc6 (>= 2.28) but 2.24-11+deb9u4 is to be installed
                 Depends: libclamav9 (>= 0.102.2) but it is not going to be installed
                 Depends: libcurl4 (>= 7.18.2) but it is not installable
                 Depends: libncurses6 (>= 6) but it is not installable
                 Depends: libtinfo6 (>= 6) but it is not installable
                 Recommends: clamdscan but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get install -y graphviz clamav clamav-daemon zip unzip aspell-es' returned a non-zero code: 100
```

**Comment by jobcespedes** [comment]
Hi, 

Would you mind sharing the output of `docker info`?

**Comment by pol-todo** [comment]
Absolutely:


Client:
 Debug Mode: false

Server:
 Containers: 29
  Running: 6
  Paused: 0
  Stopped: 23
 Images: 305
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries
splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: R5GQ:RI6L:ZB5H:7OLC:BMCZ:6WFN:CWXJ:3BOS:KRPJ:RUVF:GSQU:5XHW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 84
  Goroutines: 89
  System Time: 2020-03-12T01:03:08.7670572Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by jobcespedes** [comment]
Please try pulling latest commit. 
If needed, use `docker-compose build --no-cache php-fpm`

**Comment by pol-todo** [comment]
It works! Thank you so much for working this out.

There seems to be a little trouble in the db, but as a moodle noob, not
sure if this is an acceptable error:

**Comment by pol-todo** [comment]
My screenshot didn't go through, reposting the text: 

> postgres_1  | ERROR:  no existe la relación «mdl_context» en carácter 24
postgres_1  | SENTENCIA:  SELECT COUNT('x') FROM mdl_context
postgres_1  | ERROR:  no existe la relación «mdl_course» en carácter 15
postgres_1  | SENTENCIA:  SELECT * FROM mdl_course WHERE category = $1
cron_1      | Mar 14 19:37:01 d574111cf5d6 CRON[27]: (www-data) CMD (/usr/local/bin/php  /var/www/html/admin/cli/cron.php >/dev/null 2>&1)
cron_1      | Mar 14 19:38:01 d574111cf5d6 CRON[30]: (www-data) CMD (/usr/local/bin/php  /var/www/html/admin/cli/cron.php >/dev/null 2>&1)

**Comment by jobcespedes** [comment]
In an empty new environment, you'll need to go through Moodle install steps
to populate DB.

**Comment by pol-todo** [comment]
Understood. Thanks again!
