### ISSUE TITLE
Xdebug could not open the remote debug file

### ISSUE THREAD

**Issue by pol-todo** [jobcespedes/docker-compose-moodle#6]
Hi Job, 

I'm getting this error next:

> Got error 'PHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'.\nPHP message: Xdebug could not open the remote debug file '/var/log/xdebug.log'.\n', referer: http://localhost/my/

I'm assuming this means a folder + file on my local machine so I've set the permissions to 766 / 777 respectively and there doesn't seem to make a difference. 

Recommendations?

- Paul

**Comment by pol-todo** [comment]
(Both containers, apache and php-fpm_1, are complaining)

**Comment by jobcespedes** [comment]
Xdebug is looking for it inside the php-fpm container but cannot access it,
so the complain. If you don't need to look into the debug file (xdebug is
working), it is save to ignore the message.

**Comment by pol-todo** [comment]
Ohh, that's great insight for me. I didn't consider that container. 

Yeah, XDebug isn't working correctly and wanted to check the logs.
