### ISSUE TITLE
No puedo configurar SMTP

### ISSUE THREAD

**Issue by jcarriagc** [jobcespedes/docker-compose-moodle#8]
Hola, no puedo enviar correos debido a que al configurar smtp, no se logran enviar el email de prueba. alguna variable de entorno a configurar?

**Comment by jobcespedes** [comment]
Hola,

Me parece que no es un problema de los contenedores y tiene que ver con la config de Moodle. El siguiente enlace le podría ayudar en ese caso:

https://docs.moodle.org/35/en/Debugging#More_tools_for_debugging_outgoing_mail_.28SMTP.29
