### ISSUE TITLE
No levanta el contenedor moodle (app)

### ISSUE THREAD

**Issue by nicoLedesma** [jobcespedes/docker-compose-moodle#9]
Hello, I need your help since when doing a docker-compose ps, the app container (/ true) has the status Exit 0.
The rest of the containers are Up. Docker-compose logs don't give me any errors. Could you guide me where I am failing ?.

Data:
    Linux: Linux 4.4.0-177-generic # 207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020 x86_64 x86_64 x86_64 GNU / Linux

    Docker: Docker version 17.05.0-ce, build 89658be

    Docker-compose: docker-compose version 1.21.0, build 5920eb0

    docker-compose ps:
    Name Command State Ports
    moodle_35stable_apache2_1 / opt / docker / bin / entrypoint ... Up 443 / tcp, 127.0.0.1:8085->80/tcp
    moodle_35stable_app_1 / true Exit 0
    moodle_35stable_cron_1 php-fpm-xdebug-entrypoint ... Up 9000 / tcp
    moodle_35stable_pgadmin_1 python ./usr/local/lib/pyt ... Up 127.0.0.1:5050->80/tcp
    moodle_35stable_php-fpm_1 php-fpm-xdebug-entrypoint ... Up 9000 / tcp
    moodle_35stable_postgres_1 docker-entrypoint.sh postgres Up 5432 / tcp

    docker-compose logs --tail = "30" app:
    Attaching to moodle_35stable_app_1

Thank you very much for your help.

**Comment by jobcespedes** [comment]
Hi,

Exit 0 is the right code for the app container. It is a container to share a common bind with others.

**Comment by nicoLedesma** [comment]
Thanks!!
